version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://jafar:0258@db/test_db"
  
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jafar
      POSTGRES_PASSWORD: 0258
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
